// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package layout

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import (
	"github.com/a-h/templ"
	templruntime "github.com/a-h/templ/runtime"
)

// ThemeKey is the localStorage key used to persist domain1's selected theme.
// The domain1 prefix avoids collisions with other sites on the same origin.
//
// NOTE: these constants document the values hard-coded in the inline scripts
// below. templ treats <script> element content as raw text (not templ
// expressions), so { ThemeKey } would be emitted verbatim as a JS object
// literal and throw a ReferenceError at runtime. The values must therefore be
// written directly into the script body.
const ThemeKey = "domain1.theme"

// LightTheme/DarkTheme mirror the daisyUI theme names used by the site. The
// server renders pages with LightTheme by default (see sites/sites.go); the
// toggle overrides to DarkTheme when checked.
const (
	LightTheme = "nord"
	DarkTheme  = "nord-dark"
)

// ThemeRestoreScript runs synchronously in <head>-equivalent position so the
// saved theme is applied to <html> before first paint, preventing a flash of
// the wrong theme on reload.
func ThemeRestoreScript() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<script nonce=\"\">\n\t\t(function () {\n\t\t\ttry {\n\t\t\t\tvar t = localStorage.getItem(\"domain1.theme\");\n\t\t\t\tif (t === \"nord\" || t === \"nord-dark\") {\n\t\t\t\t\tdocument.documentElement.setAttribute(\"data-theme\", t);\n\t\t\t\t}\n\t\t\t} catch (e) {\n\t\t\t\t/* storage disabled */\n\t\t\t}\n\t\t})();\n\t</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// ThemePersistScript runs after the body renders. It syncs the navbar toggle's
// checked state with the restored theme and writes the active theme to
// localStorage whenever the user toggles it.
func ThemePersistScript() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<script nonce=\"\">\n\t\t(function () {\n\t\t\tvar cb = document.getElementById(\"theme-toggle\");\n\t\t\tif (!cb) return;\n\t\t\tcb.checked =\n\t\t\t\tdocument.documentElement.getAttribute(\"data-theme\") === \"nord-dark\";\n\t\t\tcb.addEventListener(\"change\", function () {\n\t\t\t\tvar next = cb.checked ? \"nord-dark\" : \"nord\";\n\t\t\t\tdocument.documentElement.setAttribute(\"data-theme\", next);\n\t\t\t\ttry {\n\t\t\t\t\tlocalStorage.setItem(\"domain1.theme\", next);\n\t\t\t\t} catch (e) {}\n\t\t\t});\n\t\t})();\n\t</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
