// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package main

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import (
	"github.com/a-h/templ"
	templruntime "github.com/a-h/templ/runtime"
)

import "github.com/geoffjay/jughead/templates/components/daisyui"

// introPage renders the Introduction page body. It is injected into the
// documentation layout's main region via the Page.Body factory.
func introPage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<article class=\"prose max-w-none\"><h1 class=\"text-3xl font-bold mb-2\">Introduction</h1><p class=\"text-base-content/70 mb-6\">jughead is an opinionated starter kit for multi-tenant web apps built with Go, templ, htmx, and daisyUI. This is the documentation site.</p><h2 class=\"text-xl font-semibold mt-8 mb-2\">What's inside</h2><ul class=\"list-disc pl-6 space-y-1\"><li>Multi-site routing with per-site themes and templates</li><li>GitHub OAuth and session-based authentication</li><li>An admin panel for managing sites and users</li><li>A daisyUI component library and templ layout system</li></ul><h2 class=\"text-xl font-semibold mt-8 mb-2\">Layouts</h2><p class=\"mb-4\">This page is rendered through the <code class=\"kbd kbd-sm\">templates/layouts/documentation</code> layout, a configurable documentation shell with a sidebar, main content region, and optional table of contents.</p></article>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// installPage renders the Installation page body.
func installPage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<article class=\"prose max-w-none\"><h1 class=\"text-3xl font-bold mb-2\">Installation</h1><p class=\"text-base-content/70 mb-6\">Clone the repository and run the server locally.</p><div class=\"not-prose\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = daisyui.Code(daisyui.CodeConfig{
			Class: "w-full",
			Lines: []daisyui.CodeLine{
				{Prefix: "$", Text: "git clone https://github.com/geoffjay/jughead.git"},
				{Prefix: "$", Text: "cd jughead"},
				{Prefix: "$", Text: "go run ."},
			},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div><p>The server starts on <code class=\"kbd kbd-sm\">:9000</code>.</p></article>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// architecturePage renders the Architecture page body.
func architecturePage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<article class=\"prose max-w-none\"><h1 class=\"text-3xl font-bold mb-2\">Architecture</h1><p class=\"text-base-content/70 mb-6\">jughead is structured around sites, layouts, and a shared component library.</p><h2 class=\"text-xl font-semibold mt-8 mb-2\">Sites</h2><p class=\"mb-4\">Each site lives under <code>sites/&lt;tld&gt;/&lt;domain&gt;</code> and registers a path, URL, theme, template, and optional routes with the SiteManager.</p><h2 class=\"text-xl font-semibold mt-8 mb-2\">Layouts</h2><p class=\"mb-4\">Layouts in <code>templates/layouts</code> are reusable page shells for categories of site. The documentation layout renders a navbar, sidebar, content region, and footer from a single Config struct.</p></article>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// routesPage renders the Site routes reference page body.
func routesPage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var4 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var4 == nil {
			templ_7745c5c3_Var4 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<article class=\"prose max-w-none\"><h1 class=\"text-3xl font-bold mb-2\">Site routes</h1><p class=\"text-base-content/70 mb-6\">Sites are served under <code>/sites/&lt;host&gt;</code> and reverse-proxied to their FQDN via the host map built by the SiteManager.</p><h2 class=\"text-xl font-semibold mt-8 mb-2\">Registration</h2><p class=\"mb-4\">A site is registered in <code>sites/sites.go</code> with a Path, Url, Theme, Template, and optional Routes/Auth fields. The SiteManager wires auth middleware and routes onto each site group at startup.</p></article>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// pluginsPage renders the Plugins reference page body.
func pluginsPage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var5 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var5 == nil {
			templ_7745c5c3_Var5 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<article class=\"prose max-w-none\"><h1 class=\"text-3xl font-bold mb-2\">Plugins</h1><p class=\"text-base-content/70 mb-6\">jughead loads runtime plugins (Go shared objects) at startup so auth providers and sites can be developed in separate repositories and served alongside the built-in ones without modifying the core.</p><h2 class=\"text-xl font-semibold mt-8 mb-2\">How it works</h2><p class=\"mb-4\">Set <code class=\"kbd kbd-sm\">JUGHEAD_PLUGINS_DIR</code> to a directory containing <code>*.so</code> files. The host opens each with the Go <code>plugin</code> package, looks up a symbol named <code>Plugin</code> of type <code>*sdk.Plugin</code>, and registers its <code>Providers</code> into the auth registry and its <code>Sites</code> into the SiteManager. Plugins load <em>before</em> built-in providers and <em>before</em> site initialization, so a plugin provider can override a built-in of the same name and a plugin site can reference a provider shipped by the same plugin.</p><h2 class=\"text-xl font-semibold mt-8 mb-2\">The contract</h2><p class=\"mb-4\">Plugins are built against the <code>sdk</code> package, which defines the canonical <code>Plugin</code>, <code>Site</code>, and (via <code>sdk/auth</code>) <code>Provider</code>, <code>ProviderInstance</code>, and <code>AuthConfig</code> types. A plugin is a <code>package main</code> that exports:</p><div class=\"not-prose\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = daisyui.Code(daisyui.CodeConfig{
			Class: "w-full",
			Lines: []daisyui.CodeLine{
				{Prefix: "$", Text: "var Plugin = sdk.Plugin{"},
				{Prefix: "$", Text: "  Name: \"github\","},
				{Prefix: "$", Text: "  Providers: []auth.Provider{ github.NewProvider() },"},
				{Prefix: "$", Text: "}"},
			},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</div><p class=\"mb-4\">See <code>plugins/providers/example/</code> as a minimal starter, and <code>plugins/providers/github/</code> as a real provider.</p><h2 class=\"text-xl font-semibold mt-8 mb-2\">Building</h2><p class=\"mb-4\">Plugins require CGO and must be built with the same Go toolchain version and identical dependency versions as the host (a hard requirement of the <code>plugin</code> package; mismatches panic at load time). Use the Taskfile targets, which build against the pinned <code>go.mod</code>:</p><div class=\"not-prose\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = daisyui.Code(daisyui.CodeConfig{
			Class: "w-full",
			Lines: []daisyui.CodeLine{
				{Prefix: "$", Text: "task plugin NAME=providers/github   # build one plugin"},
				{Prefix: "$", Text: "task plugins                       # build every plugin"},
				{Prefix: "$", Text: "task build:plugins                 # host binary that can load plugins"},
			},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</div><h2 class=\"text-xl font-semibold mt-8 mb-2\">Deploying</h2><p class=\"mb-4\">The default <code>Dockerfile</code> builds a static binary (<code>CGO_ENABLED=0</code>) that cannot load plugins. Use <code>Dockerfile.plugins</code>, which enables CGO and uses a glibc-based builder so the host and plugin <code>.so</code> files share a compatible C runtime. Drop <code>*.so</code> files into <code>/plugins</code> and set <code>JUGHEAD_PLUGINS_DIR=/plugins</code>.</p><p class=\"mb-4\">Linux and macOS are supported. Windows deployments fall back to the built-in providers and in-repo sites (the <code>plugin</code> package is unavailable there).</p><h2 class=\"text-xl font-semibold mt-8 mb-2\">Strict mode</h2><p class=\"mb-4\">By default a plugin that fails to load is logged and skipped so one bad <code>.so</code> doesn't stop the server. Set <code class=\"kbd kbd-sm\">JUGHEAD_PLUGINS_STRICT=1</code> to make the first load error fatal — useful in CI to catch version drift early.</p></article>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// IntroPlaceholder is the fallback Site.Template for the docs site, rendered
// by siteViewHandler when the site's Routes are not registered (e.g. dev
// fallback). It renders a minimal body so the site still responds.
func IntroPlaceholder() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var6 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var6 == nil {
			templ_7745c5c3_Var6 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "<div class=\"min-h-screen bg-base-200 text-base-content flex flex-col\"><div class=\"flex-1 grid place-content-center p-8\"><div class=\"card bg-base-100 shadow-lg max-w-lg\"><div class=\"card-body\"><h2 class=\"text-xl font-semibold mb-2\">jughead docs</h2><p class=\"text-base-content/70 mb-4\">The documentation site is being prepared. Browse the available pages once routes are registered.</p><a href=\"/\" class=\"btn btn-primary\">Go to introduction</a></div></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
