// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package domain2

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func BodyContent() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"min-h-screen w-full bg-base-200 text-base-content p-8\"><div class=\"mx-auto max-w-2xl space-y-6\"><h1 class=\"text-4xl font-bold text-primary\">domain2.tld</h1><p class=\"text-base-content/70\">This site is rendered with the daisyUI theme assigned in <code class=\"bg-base-300 px-1 rounded\">sites/sites.go</code>.</p><div class=\"card bg-base-100 shadow-lg border border-base-300\"><div class=\"card-body\"><h2 class=\"card-title text-secondary\">Theme preview</h2><p>Theme-aware elements below should visibly shift between light and dark.</p><div class=\"flex gap-2 pt-2\"><button class=\"btn btn-primary\">Primary</button> <button class=\"btn btn-secondary\">Secondary</button> <button class=\"btn btn-accent\">Accent</button> <button class=\"btn btn-neutral\">Neutral</button></div><div class=\"flex gap-2 pt-2\"><span class=\"badge badge-primary\">primary</span> <span class=\"badge badge-secondary\">secondary</span> <span class=\"badge badge-accent\">accent</span> <span class=\"badge badge-error\">error</span> <span class=\"badge badge-warning\">warning</span> <span class=\"badge badge-success\">success</span></div></div></div><div class=\"alert alert-info\"><span>If this block has a dark background and light text, the <strong>dark</strong> theme is active.</span></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
