package db

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/google/uuid"

	"github.com/jackc/pgx/v5"
)

// InvitationRepository provides access to the invitations table.
//
// The invitations_visible policy restricts rows to the active organization, so
// callers must set the OrganizationID scope via WithOrgContext.
type InvitationRepository struct{}

// NewInvitationRepository returns an InvitationRepository.
func NewInvitationRepository() *InvitationRepository { return &InvitationRepository{} }

// GetByID fetches a single invitation by primary key.
func (InvitationRepository) GetByID(ctx context.Context, tx pgx.Tx, id uuid.UUID) (Invitation, error) {
	const q = `
		SELECT id, organization_id, email, role, token, status, expires_at, created_at, updated_at
		FROM invitations WHERE id = $1
	`
	var inv Invitation
	err := tx.QueryRow(ctx, q, id).Scan(
		&inv.ID, &inv.OrganizationID, &inv.Email, &inv.Role, &inv.Token, &inv.Status,
		&inv.ExpiresAt, &inv.CreatedAt, &inv.UpdatedAt,
	)
	if errors.Is(err, pgx.ErrNoRows) {
		return Invitation{}, ErrNotFound
	}
	if err != nil {
		return Invitation{}, fmt.Errorf("get invitation by id: %w", err)
	}
	return inv, nil
}

// GetByToken fetches an invitation by its secure token. Used by the accept
// flow; RLS still applies, so the organization scope must be set. For a pre-
// acceptance lookup (the invitee has no session yet), use FindByToken.
func (InvitationRepository) GetByToken(ctx context.Context, tx pgx.Tx, token string) (Invitation, error) {
	const q = `
		SELECT id, organization_id, email, role, token, status, expires_at, created_at, updated_at
		FROM invitations WHERE token = $1
	`
	var inv Invitation
	err := tx.QueryRow(ctx, q, token).Scan(
		&inv.ID, &inv.OrganizationID, &inv.Email, &inv.Role, &inv.Token, &inv.Status,
		&inv.ExpiresAt, &inv.CreatedAt, &inv.UpdatedAt,
	)
	if errors.Is(err, pgx.ErrNoRows) {
		return Invitation{}, ErrNotFound
	}
	if err != nil {
		return Invitation{}, fmt.Errorf("get invitation by token: %w", err)
	}
	return inv, nil
}

// ListByOrganization returns all invitations for the active organization.
func (InvitationRepository) ListByOrganization(ctx context.Context, tx pgx.Tx, orgID uuid.UUID) ([]Invitation, error) {
	const q = `
		SELECT id, organization_id, email, role, token, status, expires_at, created_at, updated_at
		FROM invitations WHERE organization_id = $1 ORDER BY created_at
	`
	rows, err := tx.Query(ctx, q, orgID)
	if err != nil {
		return nil, fmt.Errorf("list invitations by org: %w", err)
	}
	defer rows.Close()

	var out []Invitation
	for rows.Next() {
		var inv Invitation
		if err := rows.Scan(
			&inv.ID, &inv.OrganizationID, &inv.Email, &inv.Role, &inv.Token, &inv.Status,
			&inv.ExpiresAt, &inv.CreatedAt, &inv.UpdatedAt,
		); err != nil {
			return nil, fmt.Errorf("scan invitation: %w", err)
		}
		out = append(out, inv)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterate invitations: %w", err)
	}
	return out, nil
}

// Create inserts a new invitation. The token must be a cryptographically-random
// string generated by the caller; expiresAt defines the acceptance window.
func (InvitationRepository) Create(
	ctx context.Context,
	tx pgx.Tx,
	orgID uuid.UUID,
	email string,
	role MembershipRole,
	token string,
	expiresAt time.Time,
) (Invitation, error) {
	const q = `
		INSERT INTO invitations (organization_id, email, role, token, expires_at)
		VALUES ($1, $2, $3, $4, $5)
		RETURNING id, organization_id, email, role, token, status, expires_at, created_at, updated_at
	`
	var inv Invitation
	err := tx.QueryRow(ctx, q, orgID, email, role, token, expiresAt).Scan(
		&inv.ID, &inv.OrganizationID, &inv.Email, &inv.Role, &inv.Token, &inv.Status,
		&inv.ExpiresAt, &inv.CreatedAt, &inv.UpdatedAt,
	)
	if err != nil {
		return Invitation{}, fmt.Errorf("create invitation: %w", err)
	}
	return inv, nil
}

// UpdateStatus transitions an invitation's lifecycle state.
func (InvitationRepository) UpdateStatus(ctx context.Context, tx pgx.Tx, id uuid.UUID, status InvitationStatus) error {
	const q = `UPDATE invitations SET status = $2 WHERE id = $1`
	ct, err := tx.Exec(ctx, q, id, status)
	if err != nil {
		return fmt.Errorf("update invitation status: %w", err)
	}
	if ct.RowsAffected() == 0 {
		return ErrNotFound
	}
	return nil
}

// Delete removes an invitation.
func (InvitationRepository) Delete(ctx context.Context, tx pgx.Tx, id uuid.UUID) error {
	const q = `DELETE FROM invitations WHERE id = $1`
	ct, err := tx.Exec(ctx, q, id)
	if err != nil {
		return fmt.Errorf("delete invitation: %w", err)
	}
	if ct.RowsAffected() == 0 {
		return ErrNotFound
	}
	return nil
}
