// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import (
	"github.com/a-h/templ"
	templruntime "github.com/a-h/templ/runtime"
)

import (
	"github.com/geoffjay/jughead/sites/links"
	"github.com/geoffjay/jughead/templates/components/daisyui"
)

func CountdownPage(r links.LinkResolver) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = pageShell(r, "Countdown", "Countdown gives you a transition effect when you change a number between 0 to 999.", countdownBody(r)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func countdownBody(r links.LinkResolver) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = section("Countdown", daisyui.Countdown(daisyui.CountdownConfig{
			Items: []daisyui.CountdownItem{{Value: "59"}},
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = section("Large text with 2 digits", daisyui.Countdown(daisyui.CountdownConfig{
			Class: "font-mono text-6xl",
			Items: []daisyui.CountdownItem{{Value: "59", Digits: "2"}},
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = section("Clock countdown", daisyui.Countdown(daisyui.CountdownConfig{
			Class: "font-mono text-2xl",
			Items: []daisyui.CountdownItem{
				{Value: "10", Suffix: "h "},
				{Value: "24", Suffix: "m "},
				{Value: "59", Suffix: "s"},
			},
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = section("Clock countdown with colons", daisyui.Countdown(daisyui.CountdownConfig{
			Class: "font-mono text-2xl",
			Items: []daisyui.CountdownItem{
				{Value: "10", Suffix: ":"},
				{Value: "24", Digits: "2", Suffix: ":"},
				{Value: "59", Digits: "2"},
			},
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = section("Large text with labels", templ.Raw(`
		<div class="flex gap-5">
			<div>
				<span class="font-mono text-4xl countdown">
					<span style="--value:15;" aria-live="polite" aria-label="15">15</span>
				</span>
				days
			</div>
			<div>
				<span class="font-mono text-4xl countdown">
					<span style="--value:10;" aria-live="polite" aria-label="10">10</span>
				</span>
				hours
			</div>
			<div>
				<span class="font-mono text-4xl countdown">
					<span style="--value:24;" aria-live="polite" aria-label="24">24</span>
				</span>
				minutes
			</div>
			<div>
				<span class="font-mono text-4xl countdown">
					<span style="--value:59;" aria-live="polite" aria-label="59">59</span>
				</span>
				sec
			</div>
		</div>`)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = section("Large text with labels under", templ.Raw(`
		<div class="grid grid-flow-col gap-5 text-center auto-cols-max">
			<div class="flex flex-col">
				<span class="font-mono text-5xl countdown">
					<span style="--value:15;" aria-live="polite" aria-label="15">15</span>
				</span>
				days
			</div>
			<div class="flex flex-col">
				<span class="font-mono text-5xl countdown">
					<span style="--value:10;" aria-live="polite" aria-label="10">10</span>
				</span>
				hours
			</div>
			<div class="flex flex-col">
				<span class="font-mono text-5xl countdown">
					<span style="--value:24;" aria-live="polite" aria-label="24">24</span>
				</span>
				min
			</div>
			<div class="flex flex-col">
				<span class="font-mono text-5xl countdown">
					<span style="--value:59;" aria-live="polite" aria-label="59">59</span>
				</span>
				sec
			</div>
		</div>`)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = section("In boxes", templ.Raw(`
		<div class="grid grid-flow-col gap-5 text-center auto-cols-max">
			<div class="flex flex-col p-2 bg-neutral rounded-box text-neutral-content">
				<span class="font-mono text-5xl countdown">
					<span style="--value:15;" aria-live="polite" aria-label="15">15</span>
				</span>
				days
			</div>
			<div class="flex flex-col p-2 bg-neutral rounded-box text-neutral-content">
				<span class="font-mono text-5xl countdown">
					<span style="--value:10;" aria-live="polite" aria-label="10">10</span>
				</span>
				hours
			</div>
			<div class="flex flex-col p-2 bg-neutral rounded-box text-neutral-content">
				<span class="font-mono text-5xl countdown">
					<span style="--value:24;" aria-live="polite" aria-label="24">24</span>
				</span>
				min
			</div>
			<div class="flex flex-col p-2 bg-neutral rounded-box text-neutral-content">
				<span class="font-mono text-5xl countdown">
					<span style="--value:59;" aria-live="polite" aria-label="59">59</span>
				</span>
				sec
			</div>
		</div>`)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
