// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import (
	"github.com/a-h/templ"
	templruntime "github.com/a-h/templ/runtime"
)

import "github.com/geoffjay/jughead/sites/links"

func DividerPage(r links.LinkResolver) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = pageShell(r, "Divider", "Divider will be used to separate content vertically or horizontally.", dividerBody(r)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func dividerBody(r links.LinkResolver) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = section("Divider", `<div class="flex flex-col w-full">
	<div class="grid h-20 card bg-base-300 rounded-box place-items-center">content</div>
	<div class="divider">OR</div>
	<div class="grid h-20 card bg-base-300 rounded-box place-items-center">content</div>
</div>`, templ.Raw(`
		<div class="flex flex-col w-full">
			<div class="grid h-20 card bg-base-300 rounded-box place-items-center">content</div>
			<div class="divider">OR</div>
			<div class="grid h-20 card bg-base-300 rounded-box place-items-center">content</div>
		</div>`)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = section("Divider horizontal", `<div class="flex w-full">
	<div class="grid h-20 grow card bg-base-300 rounded-box place-items-center">content</div>
	<div class="divider divider-horizontal">OR</div>
	<div class="grid h-20 grow card bg-base-300 rounded-box place-items-center">content</div>
</div>`, templ.Raw(`
		<div class="flex w-full">
			<div class="grid h-20 grow card bg-base-300 rounded-box place-items-center">content</div>
			<div class="divider divider-horizontal">OR</div>
			<div class="grid h-20 grow card bg-base-300 rounded-box place-items-center">content</div>
		</div>`)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = section("Divider with no text", `<div class="flex flex-col w-full">
	<div class="grid h-20 card bg-base-300 rounded-box place-items-center">content</div>
	<div class="divider"></div>
	<div class="grid h-20 card bg-base-300 rounded-box place-items-center">content</div>
</div>`, templ.Raw(`
		<div class="flex flex-col w-full">
			<div class="grid h-20 card bg-base-300 rounded-box place-items-center">content</div>
			<div class="divider"></div>
			<div class="grid h-20 card bg-base-300 rounded-box place-items-center">content</div>
		</div>`)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = section("Responsive (lg:divider-horizontal)", `<div class="flex flex-col w-full lg:flex-row">
	<div class="grid grow h-32 card bg-base-300 rounded-box place-items-center">content</div>
	<div class="divider lg:divider-horizontal">OR</div>
	<div class="grid grow h-32 card bg-base-300 rounded-box place-items-center">content</div>
</div>`, templ.Raw(`
		<div class="flex flex-col w-full lg:flex-row">
			<div class="grid grow h-32 card bg-base-300 rounded-box place-items-center">content</div>
			<div class="divider lg:divider-horizontal">OR</div>
			<div class="grid grow h-32 card bg-base-300 rounded-box place-items-center">content</div>
		</div>`)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = section("Divider with colors", `<div class="flex flex-col w-full">
	<div class="divider">Default</div>
	<div class="divider divider-neutral">Neutral</div>
	<div class="divider divider-primary">Primary</div>
	<div class="divider divider-secondary">Secondary</div>
	<div class="divider divider-accent">Accent</div>
	<div class="divider divider-success">Success</div>
	<div class="divider divider-warning">Warning</div>
	<div class="divider divider-info">Info</div>
	<div class="divider divider-error">Error</div>
</div>`, templ.Raw(`
		<div class="flex flex-col w-full">
			<div class="divider">Default</div>
			<div class="divider divider-neutral">Neutral</div>
			<div class="divider divider-primary">Primary</div>
			<div class="divider divider-secondary">Secondary</div>
			<div class="divider divider-accent">Accent</div>
			<div class="divider divider-success">Success</div>
			<div class="divider divider-warning">Warning</div>
			<div class="divider divider-info">Info</div>
			<div class="divider divider-error">Error</div>
		</div>`)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = section("Divider in different positions", `<div class="flex flex-col w-full">
	<div class="divider divider-start">Start</div>
	<div class="divider">Default</div>
	<div class="divider divider-end">End</div>
</div>`, templ.Raw(`
		<div class="flex flex-col w-full">
			<div class="divider divider-start">Start</div>
			<div class="divider">Default</div>
			<div class="divider divider-end">End</div>
		</div>`)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = section("Divider in different positions (horizontal)", `<div class="flex w-full justify-center h-52">
	<div class="divider divider-horizontal divider-start">Start</div>
	<div class="divider divider-horizontal">Default</div>
	<div class="divider divider-horizontal divider-end">End</div>
</div>`, templ.Raw(`
		<div class="flex w-full justify-center h-52">
			<div class="divider divider-horizontal divider-start">Start</div>
			<div class="divider divider-horizontal">Default</div>
			<div class="divider divider-horizontal divider-end">End</div>
		</div>`)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
