// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import (
	"github.com/a-h/templ"
	templruntime "github.com/a-h/templ/runtime"
)

import (
	"github.com/geoffjay/jughead/sites/links"
	"github.com/geoffjay/jughead/templates/components/daisyui"
)

func DropdownPage(r links.LinkResolver) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = pageShell(r, "Dropdown", "Dropdown opens a menu or panel of options on hover or click.", dropdownBody(r)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func dropdownBody(r links.LinkResolver) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = section("Dropdown", `@daisyui.Dropdown(daisyui.DropdownConfig{
	Label:    "Click me",
	Items:    []daisyui.DropdownItem{{Label: "Item 1", Href: "#"}, {Label: "Item 2", Href: "#"}},
	Resolver: r,
})`, daisyui.Dropdown(daisyui.DropdownConfig{
			Label:    "Click me",
			Items:    []daisyui.DropdownItem{{Label: "Item 1", Href: "#"}, {Label: "Item 2", Href: "#"}},
			Resolver: r,
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = section("Dropdown with hover", `@daisyui.Dropdown(daisyui.DropdownConfig{
	Label:    "Hover me",
	Modifier: "hover",
	Items:    []daisyui.DropdownItem{{Label: "Item 1", Href: "#"}, {Label: "Item 2", Href: "#"}},
	Resolver: r,
})`, daisyui.Dropdown(daisyui.DropdownConfig{
			Label:    "Hover me",
			Modifier: "hover",
			Items:    []daisyui.DropdownItem{{Label: "Item 1", Href: "#"}, {Label: "Item 2", Href: "#"}},
			Resolver: r,
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = section("Dropdown open", `@daisyui.Dropdown(daisyui.DropdownConfig{
	Label:    "Always open",
	Modifier: "open",
	Items:    []daisyui.DropdownItem{{Label: "Item 1", Href: "#"}, {Label: "Item 2", Href: "#"}},
	Resolver: r,
})`, daisyui.Dropdown(daisyui.DropdownConfig{
			Label:    "Always open",
			Modifier: "open",
			Items:    []daisyui.DropdownItem{{Label: "Item 1", Href: "#"}, {Label: "Item 2", Href: "#"}},
			Resolver: r,
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = section("Dropdown with details/summary", `@daisyui.Dropdown(daisyui.DropdownConfig{
	Label:      "Details trigger",
	UseDetails: true,
	Items:      []daisyui.DropdownItem{{Label: "Item 1", Href: "#"}, {Label: "Item 2", Href: "#"}},
	Resolver:   r,
})`, daisyui.Dropdown(daisyui.DropdownConfig{
			Label:      "Details trigger",
			UseDetails: true,
			Items:      []daisyui.DropdownItem{{Label: "Item 1", Href: "#"}, {Label: "Item 2", Href: "#"}},
			Resolver:   r,
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = section("Dropdown placement (top end)", `@daisyui.Dropdown(daisyui.DropdownConfig{
	Label:     "Top end",
	Placement: "top end",
	Items:     []daisyui.DropdownItem{{Label: "Item 1", Href: "#"}, {Label: "Item 2", Href: "#"}},
	Resolver:  r,
})`, daisyui.Dropdown(daisyui.DropdownConfig{
			Label:     "Top end",
			Placement: "top end",
			Items:     []daisyui.DropdownItem{{Label: "Item 1", Href: "#"}, {Label: "Item 2", Href: "#"}},
			Resolver:  r,
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = section("Dropdown placement (bottom center)", `@daisyui.Dropdown(daisyui.DropdownConfig{
	Label:     "Bottom center",
	Placement: "bottom center",
	Items:     []daisyui.DropdownItem{{Label: "Item 1", Href: "#"}, {Label: "Item 2", Href: "#"}},
	Resolver:  r,
})`, daisyui.Dropdown(daisyui.DropdownConfig{
			Label:     "Bottom center",
			Placement: "bottom center",
			Items:     []daisyui.DropdownItem{{Label: "Item 1", Href: "#"}, {Label: "Item 2", Href: "#"}},
			Resolver:  r,
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = section("Dropdown with custom trigger class", `@daisyui.Dropdown(daisyui.DropdownConfig{
	Label:        "Custom trigger",
	TriggerClass: "btn btn-primary",
	Items:        []daisyui.DropdownItem{{Label: "Item 1", Href: "#"}, {Label: "Item 2", Href: "#"}},
	Resolver:     r,
})`, daisyui.Dropdown(daisyui.DropdownConfig{
			Label:        "Custom trigger",
			TriggerClass: "btn btn-primary",
			Items:        []daisyui.DropdownItem{{Label: "Item 1", Href: "#"}, {Label: "Item 2", Href: "#"}},
			Resolver:     r,
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = section("Dropdown with buttons (no href)", `@daisyui.Dropdown(daisyui.DropdownConfig{
	Label: "Buttons",
	Items: []daisyui.DropdownItem{{Label: "Action 1"}, {Label: "Action 2"}, {Label: "Action 3"}},
})`, daisyui.Dropdown(daisyui.DropdownConfig{
			Label: "Buttons",
			Items: []daisyui.DropdownItem{{Label: "Action 1"}, {Label: "Action 2"}, {Label: "Action 3"}},
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = section("Dropdown with custom content", `@daisyui.Dropdown(daisyui.DropdownConfig{
	Label:   "Custom content",
	Content: dropdownCustomCard(),
})`, daisyui.Dropdown(daisyui.DropdownConfig{
			Label:   "Custom content",
			Content: dropdownCustomCard(),
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = section("Dropdown with items + resolver", `@daisyui.Dropdown(daisyui.DropdownConfig{
	Label:    "Resolved links",
	Items:    []daisyui.DropdownItem{{Label: "Home", Href: "/"}, {Label: "About", Href: "/about"}, {Label: "Contact", Href: "/contact"}},
	Resolver: r,
})`, daisyui.Dropdown(daisyui.DropdownConfig{
			Label:    "Resolved links",
			Items:    []daisyui.DropdownItem{{Label: "Home", Href: "/"}, {Label: "About", Href: "/about"}, {Label: "Contact", Href: "/contact"}},
			Resolver: r,
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func dropdownCustomCard() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"card card-compact w-64 bg-base-100 shadow-sm\"><div class=\"card-body\"><h3 class=\"card-title\">Card dropdown</h3><p class=\"text-sm opacity-70\">Any templ component can be rendered inside a dropdown.</p><div class=\"card-actions justify-end\"><button class=\"btn btn-primary btn-sm\">Close</button></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
