// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import (
	"github.com/a-h/templ"
	templruntime "github.com/a-h/templ/runtime"
)

import (
	"github.com/geoffjay/jughead/sites/links"
	"github.com/geoffjay/jughead/templates/components/daisyui"
	icons "github.com/iota-uz/icons/phosphor"
)

func FABPage(r links.LinkResolver) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = pageShell(r, "FAB / Speed Dial", "FAB (Floating Action Button) stays in the bottom corner of screen. It includes a focusable and accessible element with button role. Clicking or focusing it shows additional buttons (known as Speed Dial buttons) in a vertical arrangement or a flower shape (quarter circle).", fabBody(r)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// fabFrame wraps a FAB example in a positioned container so each FAB's
// absolute positioning is scoped to its own section rather than the page.
// Without this, every FAB stacks in the page's bottom-left corner and only the
// topmost is interactive. Height mirrors the daisyUI docs (h-54; h-48 for the
// tooltip variant).
func fabFrame(title string, fab templ.Component) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"space-y-4\"><h2 class=\"text-2xl font-semibold\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `sites/tld/domain1/components/fab.templ`, Line: 20, Col: 44}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</h2><div class=\"relative h-54\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = fab.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// fabFrameShort is like fabFrame but with h-48 for the tooltip variant where
// less vertical space is needed.
func fabFrameShort(title string, fab templ.Component) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var4 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var4 == nil {
			templ_7745c5c3_Var4 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<section class=\"space-y-4\"><h2 class=\"text-2xl font-semibold\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `sites/tld/domain1/components/fab.templ`, Line: 31, Col: 44}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</h2><div class=\"relative h-48\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = fab.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// fabCircleItem builds a circular speed-dial action button with a text label.
func fabCircleItem(label string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var6 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var6 == nil {
			templ_7745c5c3_Var6 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = daisyui.Button(daisyui.ButtonConfig{Label: label, Size: "lg", Modifier: "circle"}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func fabBody(r links.LinkResolver) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var7 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var7 == nil {
			templ_7745c5c3_Var7 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = fabFrame("FAB and Speed Dial (vertical)", daisyui.FAB(daisyui.FABConfig{
			Trigger: daisyui.FABTrigger{Label: "F", Color: "primary"},
			Class:   "absolute z-1",
			Items: []daisyui.FABItem{
				{Button: fabCircleItem("A")},
				{Button: fabCircleItem("B")},
				{Button: fabCircleItem("C")},
			},
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = fabFrame("FAB and Speed Dial with SVG icons", daisyui.FAB(daisyui.FABConfig{
			Trigger: daisyui.FABTrigger{
				Color:    "secondary",
				Children: icons.Plus(icons.Props{Size: "24", Class: "size-6"}),
			},
			Class: "absolute z-1",
			Items: []daisyui.FABItem{
				{Button: daisyui.Button(daisyui.ButtonConfig{Size: "lg", Modifier: "circle", Children: icons.Camera(icons.Props{Size: "24", Class: "size-6"})})},
				{Button: daisyui.Button(daisyui.ButtonConfig{Size: "lg", Modifier: "circle", Children: icons.Image(icons.Props{Size: "24", Class: "size-6"})})},
				{Button: daisyui.Button(daisyui.ButtonConfig{Size: "lg", Modifier: "circle", Children: icons.Microphone(icons.Props{Size: "24", Class: "size-6"})})},
			},
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = fabFrame("FAB and Speed Dial with labels", daisyui.FAB(daisyui.FABConfig{
			Trigger: daisyui.FABTrigger{Label: "F", Color: "success"},
			Class:   "absolute z-1",
			Items: []daisyui.FABItem{
				{Label: "Label B", Button: fabCircleItem("A")},
				{Label: "Label C", Button: fabCircleItem("B")},
				{Label: "Label D", Button: fabCircleItem("C")},
			},
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = fabFrame("FAB and Speed Dial with rectangle buttons", daisyui.FAB(daisyui.FABConfig{
			Trigger: daisyui.FABTrigger{Label: "F", Color: "success"},
			Class:   "absolute z-1",
			Items: []daisyui.FABItem{
				{Button: daisyui.Button(daisyui.ButtonConfig{Label: "Button A", Size: "lg"})},
				{Button: daisyui.Button(daisyui.ButtonConfig{Label: "Button B", Size: "lg"})},
				{Button: daisyui.Button(daisyui.ButtonConfig{Label: "Button C", Size: "lg"})},
			},
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = fabFrame("FAB and Speed Dial with labels and fab-close button", daisyui.FAB(daisyui.FABConfig{
			Trigger:     daisyui.FABTrigger{Label: "F", Color: "info"},
			Class:       "absolute z-1",
			CloseButton: templ.Raw(`Close <span class="btn btn-circle btn-lg btn-error">✕</span>`),
			Items: []daisyui.FABItem{
				{Label: "Label A", Button: fabCircleItem("A")},
				{Label: "Label B", Button: fabCircleItem("B")},
				{Label: "Label C", Button: fabCircleItem("C")},
			},
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = fabFrame("FAB and Speed Dial with labels and fab-main-action Button", daisyui.FAB(daisyui.FABConfig{
			Trigger:    daisyui.FABTrigger{Label: "F", Color: "primary"},
			Class:      "absolute z-1",
			MainAction: templ.Raw(`Main Action <button class="btn btn-circle btn-secondary btn-lg">M</button>`),
			Items: []daisyui.FABItem{
				{Label: "Label A", Button: fabCircleItem("A")},
				{Label: "Label B", Button: fabCircleItem("B")},
				{Label: "Label C", Button: fabCircleItem("C")},
			},
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = fabFrame("A single FAB (Floating Action Button)", daisyui.FAB(daisyui.FABConfig{
			Trigger: daisyui.FABTrigger{Label: "F", Color: "primary"},
			Class:   "absolute z-1",
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = fabFrame("FAB Flower and Speed Dial", daisyui.FAB(daisyui.FABConfig{
			Trigger:    daisyui.FABTrigger{Label: "F", Color: "success"},
			Class:      "absolute z-1",
			Flower:     true,
			MainAction: daisyui.Button(daisyui.ButtonConfig{Label: "M", Size: "lg", Modifier: "circle"}),
			Items: []daisyui.FABItem{
				{Button: fabCircleItem("A")},
				{Button: fabCircleItem("B")},
				{Button: fabCircleItem("C")},
				{Button: fabCircleItem("D")},
			},
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = fabFrameShort("FAB and Flower Speed Dial with tooltip", daisyui.FAB(daisyui.FABConfig{
			Trigger:    daisyui.FABTrigger{Label: "F", Color: "info"},
			Class:      "absolute z-1",
			Flower:     true,
			MainAction: daisyui.Button(daisyui.ButtonConfig{Label: "M", Size: "lg", Modifier: "circle", Color: "success"}),
			Items: []daisyui.FABItem{
				{Button: daisyui.Tooltip(daisyui.TooltipConfig{Tip: "Label A", Position: "left", Children: fabCircleItem("A")})},
				{Button: daisyui.Tooltip(daisyui.TooltipConfig{Tip: "Label B", Position: "left", Children: fabCircleItem("B")})},
				{Button: daisyui.Tooltip(daisyui.TooltipConfig{Tip: "Label C", Children: fabCircleItem("C")})},
				{Button: daisyui.Tooltip(daisyui.TooltipConfig{Tip: "Label D", Children: fabCircleItem("D")})},
			},
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
