// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import (
	"github.com/a-h/templ"
	templruntime "github.com/a-h/templ/runtime"
)

import (
	"github.com/geoffjay/jughead/sites/links"
	"github.com/geoffjay/jughead/templates/components/daisyui"
)

func TooltipPage(r links.LinkResolver) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = pageShell(r, "Tooltip", "Tooltip can be used to show a message when hovering over an element.", tooltipBody(r)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func tooltipBody(r links.LinkResolver) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = section("Tooltip", `@daisyui.Tooltip(daisyui.TooltipConfig{
	Tip:      "hello",
	Children: templ.Raw(...),
})`, daisyui.Tooltip(daisyui.TooltipConfig{
			Tip:      "hello",
			Children: templ.Raw(`<button class="btn">Hover me</button>`),
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = section("Tooltip with tooltip-content", `@daisyui.Tooltip(daisyui.TooltipConfig{
	Content:  templ.Raw(...),
	Children: templ.Raw(...),
})`, daisyui.Tooltip(daisyui.TooltipConfig{
			Content:  templ.Raw(`<div class="animate-bounce text-orange-400 -rotate-10 text-2xl font-black">Wow!</div>`),
			Children: templ.Raw(`<button class="btn">Hover me</button>`),
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = section("Force open", `@daisyui.Tooltip(daisyui.TooltipConfig{
	Tip:      "hello",
	Open:     true,
	Children: templ.Raw(...),
})`, daisyui.Tooltip(daisyui.TooltipConfig{
			Tip:      "hello",
			Open:     true,
			Children: templ.Raw(`<button class="btn">Force open</button>`),
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = section("Top", `@daisyui.Tooltip(daisyui.TooltipConfig{
	Tip: "hello", Position: "top", Open: true,
	Children: templ.Raw(...),
})`, daisyui.Tooltip(daisyui.TooltipConfig{
			Tip: "hello", Position: "top", Open: true,
			Children: templ.Raw(`<button class="btn">Top</button>`),
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = section("Bottom", `@daisyui.Tooltip(daisyui.TooltipConfig{
	Tip: "hello", Position: "bottom", Open: true,
	Children: templ.Raw(...),
})`, daisyui.Tooltip(daisyui.TooltipConfig{
			Tip: "hello", Position: "bottom", Open: true,
			Children: templ.Raw(`<button class="btn">Bottom</button>`),
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = section("Left", `@daisyui.Tooltip(daisyui.TooltipConfig{
	Tip: "hello", Position: "left", Open: true,
	Children: templ.Raw(...),
})`, daisyui.Tooltip(daisyui.TooltipConfig{
			Tip: "hello", Position: "left", Open: true,
			Children: templ.Raw(`<button class="btn">Left</button>`),
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = section("Right", `@daisyui.Tooltip(daisyui.TooltipConfig{
	Tip: "hello", Position: "right", Open: true,
	Children: templ.Raw(...),
})`, daisyui.Tooltip(daisyui.TooltipConfig{
			Tip: "hello", Position: "right", Open: true,
			Children: templ.Raw(`<button class="btn">Right</button>`),
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = section("Primary color", `@daisyui.Tooltip(daisyui.TooltipConfig{
	Tip: "primary", Color: "primary", Open: true,
	Children: templ.Raw(...),
})`, daisyui.Tooltip(daisyui.TooltipConfig{
			Tip: "primary", Color: "primary", Open: true,
			Children: templ.Raw(`<button class="btn btn-primary">primary</button>`),
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = section("Secondary color", `@daisyui.Tooltip(daisyui.TooltipConfig{
	Tip: "secondary", Color: "secondary", Open: true,
	Children: templ.Raw(...),
})`, daisyui.Tooltip(daisyui.TooltipConfig{
			Tip: "secondary", Color: "secondary", Open: true,
			Children: templ.Raw(`<button class="btn btn-secondary">secondary</button>`),
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = section("Accent color", `@daisyui.Tooltip(daisyui.TooltipConfig{
	Tip: "accent", Color: "accent", Open: true,
	Children: templ.Raw(...),
})`, daisyui.Tooltip(daisyui.TooltipConfig{
			Tip: "accent", Color: "accent", Open: true,
			Children: templ.Raw(`<button class="btn btn-accent">accent</button>`),
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = section("Info color", `@daisyui.Tooltip(daisyui.TooltipConfig{
	Tip: "info", Color: "info", Open: true,
	Children: templ.Raw(...),
})`, daisyui.Tooltip(daisyui.TooltipConfig{
			Tip: "info", Color: "info", Open: true,
			Children: templ.Raw(`<button class="btn btn-info">info</button>`),
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = section("Success color", `@daisyui.Tooltip(daisyui.TooltipConfig{
	Tip: "success", Color: "success", Open: true,
	Children: templ.Raw(...),
})`, daisyui.Tooltip(daisyui.TooltipConfig{
			Tip: "success", Color: "success", Open: true,
			Children: templ.Raw(`<button class="btn btn-success">success</button>`),
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = section("Warning color", `@daisyui.Tooltip(daisyui.TooltipConfig{
	Tip: "warning", Color: "warning", Open: true,
	Children: templ.Raw(...),
})`, daisyui.Tooltip(daisyui.TooltipConfig{
			Tip: "warning", Color: "warning", Open: true,
			Children: templ.Raw(`<button class="btn btn-warning">warning</button>`),
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = section("Error color", `@daisyui.Tooltip(daisyui.TooltipConfig{
	Tip: "error", Color: "error", Open: true,
	Children: templ.Raw(...),
})`, daisyui.Tooltip(daisyui.TooltipConfig{
			Tip: "error", Color: "error", Open: true,
			Children: templ.Raw(`<button class="btn btn-error">error</button>`),
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = section("Responsive tooltip. only show for large screen", `@daisyui.Tooltip(daisyui.TooltipConfig{
	Tip:      "hello",
	Class:    "lg:tooltip",
	Children: templ.Raw(...),
})`, daisyui.Tooltip(daisyui.TooltipConfig{
			Tip:      "hello",
			Class:    "lg:tooltip",
			Children: templ.Raw(`<button class="btn">Hover me</button>`),
		})).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
